# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Docs for xbool
dev_addr: 127.0.0.1:7000

nav:
  - xbool:
    - index.md
  - API Reference: api/xbool/" target="_blank
  - Changelog: changelog.md

theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
#    - header.autohide
    - navigation.sections
    - navigation.expand
    - navigation.top
#    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
#  logo: media/aws-logo-light.svg
#  favicon: media/aws-logo-light.svg
#  custom_dir: docs/overrides
markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: "."
      check_paths: true
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.superfences:

plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
  - git-revision-date
  - search
extra:
  version:
    provider: mike
    default: latest
